---
version: '3.7'

services:

  bfe-backend:
    image: bfe-backend:latest
    container_name: bfe-backend
    restart: unless-stopped
    ports:
      - 7009:7000
    volumes:
      - ./localdev/conf/rclone.conf:/conf/rclone.conf
      - ./localdev/bfetmp:/bfetmp
      - ./localdev/data:/data
      # start preservation targets
      - ./localdev/testdata/MyOldPictures:/testdata/MyOldPictures
      - ./localdev/testdata/MyReallyOldPictures:/testdata/MyReallyOldPictures
      - ./localdev/testdata/MyReallyOldPictures:/secondmountpath/MyOtherCopyOfReallyOldPictures
      # end preservation targets

  bfe-frontend:
    image: bfe-frontend:latest
    container_name: bfe-frontend
    restart: unless-stopped
    ports:
      - 7002:80
    environment:
      - BFE_ENV_PRODUCTION=true
      - BFE_ENV_BFE_BACKEND_BASE_URL=http://localhost:7009
